sonar.projectKey=aqua-cloud_aqua-backend-ng
sonar.organization=aqua-cloud
sonar.projectName=aqua-backend-ng
sonar.sources=src
sonar.tests=tests
sonar.cs.opencover.reportsPaths=TestResults/**/coverage.opencover.xml
sonar.coverage.exclusions=**/*.Tests/**,**/Program.cs
